### ISSUE TITLE
Contributing Guidelines: Tests are required, but no tests are currently present.

### ISSUE THREAD

**Issue by parker-research** [MatheusMarinhoLeca/Easy_Pokedex#11]
The `CONTRIBUTING.md` guide says:

> Tests
>
> Always cover your code with meaningful tests.

However, I don't see a location for unit tests, nor any guideline on what is considered testable. Please advise what the policy is for this project.

**Comment by MatheusMarinhoLeca** [comment]
Ticket accepted.
