### ISSUE TITLE
Feature Request: Add link to wikipedia page for pokemon

### ISSUE THREAD

**Issue by parker-research** [MatheusMarinhoLeca/Easy_Pokedex#12]
Being able to visit the page for each Pokemon in an online resource would be helpful to fill in the missing information.

The following link is an example for the "Cofagrigus" Pokemon: https://bulbapedia.bulbagarden.net/wiki/Cofagrigus_(Pok%C3%A9mon)

This link could be automatically generated for each Pokemon.

**Comment by MatheusMarinhoLeca** [comment]
Ticket rejected.

Beyond the scope of this project.

**Comment by parker-research** [comment]
Please consider closing the issue as "not completed" instead of "closed as completed" if the item is rejected
