### ISSUE TITLE
Unit tests don't run in VS Code because execution guard not used

### ISSUE THREAD

**Issue by parker-research** [MatheusMarinhoLeca/Easy_Pokedex#15]
Currently, the entire code (including the GUI) starts when you import the `easy_pokedex` module. 

This is because, at the bottom of the Python script, you just have:

```python
main()
```

You need to check whether the file is being included as a module, or if it is being executed directly. The standard way to do that is with:

```python
if __name__ == '__main__':
    main()
```

**Comment by MatheusMarinhoLeca** [comment]
Fixed
