### ISSUE TITLE
License: Please clarify the licensing on assets stored within this repo

### ISSUE THREAD

**Issue by parker-research** [MatheusMarinhoLeca/Easy_Pokedex#9]
I don't see a mention of the source nor copyright ownership of the following assets stored within this repo:

1. PNG images 
2. `pokemon_data.json` file

Perhaps these should be loaded from an external API; otherwise, their ownership should be clarified if the "Licensing" section of the README, as well as the LICENSE file.

**Comment by MatheusMarinhoLeca** [comment]
Ticket rejected.

I am already assigning the trademarks to the owner in Licensing.

**Comment by parker-research** [comment]
The LICENSE file, as of commit 1b9c1a5, does not mention anything about trademarks; it is a generic generation of the MIT License.

This repository is distributing unlicensed Pokemon images, as far as I can tell. 

The following line in the readme does not declare the ownership of the images stored in this repo, and simply says that you do not own the name "Pokemon":

> Pokémon and Pokémon character names are trademarks of Nintendo.
